replicaCount: 1
image:
  repository: mileagedevcr.azurecr.io/mileage-dev/backend-admin
  pullPolicy: Always
  tag: "v0.0.2"

imagePullSecrets:
  - name: acr-credential
config: 
  SERVER_GRPC_PORT: ":9091"
  DB_MAX_CONNECTION: 10
  DB_IDLE_CONNECTION: 5
  DB_CONN_MAX_IDLE_TIME: 30
  DB_CONN_MAX_LIFE_TIME: 1440
  LOCATION_CARE_TABLE: "dev_user_location_care"
  APPLOG_TABLE: "dev_user_applog"
  HEALTHCARE_PHYSIQUE_TABLE: "dev_user_healthcare_physique"
  HEALTHCARE_SLEEP_TABLE: "dev_user_healthcare_sleep"
  HEALTHCARE_SPORT_TABLE: "dev_user_healthcare_sport"
  HEALTHCARE_SCREEN_TABLE: "dev_user_healthcare_screen"
  HEALTHCARE_ACTIVITY_TABLE: "dev_user_healthcare_activity"
  HEALTHCARE_BP_TABLE: "dev_user_healthcare_bp"

grpc:
  enabled: true
  serviceType: ClusterIP  # mode ClusterIP
  ports:
    - name: grpc-admin
      port: 9091
      targetPort: 9091
      protocol: TCP

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  
service:
  type: ClusterIP
  port: 9091

ingress:
  enabled: false  # disable Ingress

istio:
  enabled: false
      
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80